### ISSUE TITLE
[Feature Request] Batch conversion

### ISSUE THREAD

**Issue by Miyuutsu** [Akegarasu/sd-webui-model-converter#10]
If it wouldn't be too much work, I'd like to request implementation of batch processing. I have a ton of models laying around and it would be wonderful to be able to use this to batch remove the VAE from them to save space. I've not seen any other tools supporting removal of VAE.

**Comment by 2blackbar** [comment]
Heres a GUI for it, you can convert one by one or choose batch ,its setup by default to just -p argument which is just prune, if you want to boot the VAE you need to edit the argument inside 
![image](https://user-images.githubusercontent.com/33694664/229827837-430a0eaf-d5ed-4148-94a3-38b30220e1ff.png)

[pgui.zip](https://github.com/Akegarasu/sd-webui-model-converter/files/11149754/pgui.zip)

**Comment by Miyuutsu** [comment]
Ah, nice! I guess I was just looking for it incorrectly. I will close this now. Thank you!
