### ISSUE TITLE
ControlNet model with .pth extension not appearing in dropdown menu

### ISSUE THREAD

**Issue by Guillaume-Fgt** [Akegarasu/sd-webui-model-converter#11]
Hi, I just want to check if it's normal behavior.

I want to convert a ControlNet model ```control_v11f1e_sd15_tile.pth``` to fp16 safetensors. I know it is possible because I downloaded some other model in this format previously (700MB vs 1.4 for the model I have).

Is is possible to do it with your extension? The model doesn't appear in the dropdown menu. I try refreshing the dropdown and restarted AUTO1111. No effects.

**Comment by Akegarasu** [comment]
it's normal behavior. this program is designed **only** for stable diffsuion checkpoints. it reads the model list from sd-webui
I can't guarantee this script will function normally when handling other models. probably it may works

**Comment by Guillaume-Fgt** [comment]
thank you for your answer.
