### ISSUE TITLE
maybe bug: fix clip may not work?

### ISSUE THREAD

**Issue by ananosleep** [Akegarasu/sd-webui-model-converter#15]
model: AnythingV3.0.ckpt[8712e20a5d]

1. 
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/435a4790-038d-42a8-8a7a-8499c9fb926b)
and I got a non-ema-pruned model which clip is not fixed.
最终得到一个没有修复clip的模型

2. 
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/c96fb276-9abe-48d5-b597-6469ed532360)
this is the report:  

Loading E:\AI\sd-webui\stable-diffusion-webui-directml(vae)\models\Stable-diffusion\Anything-V3.0.ckpt...
Converting model...
100%|████████████████████████████████████████████████████████████████████████████| 1819/1819 [00:00<00:00, 3050.14it/s]
clip in this model is fine, skip fixing...

and I got a non-ema-pruned model which clip is maybe fixed？
所以我得到了一个或许clip被修复了的模型？

3.
run these 3 models, and I got 3 same images when use same seed.
运行这3个模型，在同种子下得到了一样的结果
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/f4e8f4fc-8bfd-4704-9b77-1c670f8a3541)

4. I decided to check these 3 models' clip using model-toolkit and got a surprising result:
我决定用toolkit检测这三个模型的clip究竟是否正常，但是得到了一个令人惊讶的结果：

Anything-V3.0.ckpt [8712e20a5d]:
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/df78283a-02d2-4d1a-ada5-25639e124d8f)
Anything-V3.0-fp16-no-ema-fixed-converter.safetensors [a08c1887cf]:
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/27aed1da-8303-41f3-8085-36e22bd53183)
Anything-V3.0-fp16-no-ema-converter.safetensors [b8209f5b6a]:
![image](https://github.com/Akegarasu/sd-webui-model-converter/assets/126318157/9299c6c4-fae6-4adc-982c-2bad69c1db0a)

So, while the original model's clip has 13 wrong position, I wonder if these two pruned models' clip are fine. If they're fixed, why I got 3 same images? If they're not fixed, why this extension report clip in this model is fine, and why model-toolkit report both clips are fine?
所以，在已知原模型存在13处clip偏移的情况下（实际上a3的clip存在偏移也是众所周知的事实），我很想知道剪枝出来的两个模型clip到底正常与否。如果它们都被修复了，为什么能得到跟原模型相同的图片？如果没被修复，为什么这个插件会报clip没有问题，并且toolkit会给出这么诡异的结果？

**Comment by Akegarasu** [comment]
This is because the precision of position_id was originally fp32, and during the compression process to fp16, the precision decreased, which happened to fix the offset.
