### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by CoraAI** [Akegarasu/sd-webui-model-converter#18]
venv "D:\Ai_program\stable-diffusion-webui\venv\Scripts\Python.exe"
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing requirements
Requirement already satisfied: send2trash~=1.8 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (1.8.2)
Requirement already satisfied: dynamicprompts[attentiongrabber,magicprompt]~=0.27.0 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (0.27.0)
Requirement already satisfied: jinja2~=3.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.2)
Requirement already satisfied: pyparsing~=3.0 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.0.9)
Requirement already satisfied: transformers[torch]~=4.19 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.30.2)
Requirement already satisfied: MarkupSafe>=2.0 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from jinja2~=3.1->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.1.2)
Requirement already satisfied: filelock in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.12.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.14.1)
Requirement already satisfied: numpy>=1.17 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.23.5)
Requirement already satisfied: packaging>=20.0 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (23.1)
Requirement already satisfied: pyyaml>=5.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (6.0)
Requirement already satisfied: regex!=2019.12.17 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.5)
Requirement already satisfied: requests in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.13.3)
Requirement already satisfied: safetensors>=0.3.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.3.1)
Requirement already satisfied: tqdm>=4.27 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.65.0)
Requirement already satisfied: torch!=1.12.0,>=1.9 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.0.0+cu118)
Requirement already satisfied: accelerate>=0.20.2 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.21.0)
Requirement already satisfied: psutil in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from accelerate>=0.20.2->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (5.9.5)
Requirement already satisfied: fsspec in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from huggingface-hub<1.0,>=0.14.1->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (4.7.1)
Requirement already satisfied: sympy in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from torch!=1.12.0,>=1.9->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.11.1)
Requirement already satisfied: networkx in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from torch!=1.12.0,>=1.9->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1)
Requirement already satisfied: colorama in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from tqdm>=4.27->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (0.4.6)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (3.1.0)
Requirement already satisfied: idna<4,>=2.5 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from requests->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (2023.5.7)
Requirement already satisfied: mpmath>=0.19 in d:\ai_program\stable-diffusion-webui\venv\lib\site-packages (from sympy->torch!=1.12.0,>=1.9->transformers[torch]~=4.19->dynamicprompts[attentiongrabber,magicprompt]~=0.27.0) (1.3.0)
sd-dynamic-prompts installer: running 'D:\Ai_program\stable-diffusion-webui\venv\Scripts\python.exe' -m pip install 'send2trash~=1.8' 'dynamicprompts[attentiongrabber,magicprompt]~=0.27.0'
If submitting an issue on github, please provide the full startup log for debugging purposes.

Initializing Dreambooth
Dreambooth revision: cf086c536b141fc522ff11f6cffc8b7b12da04b9
Successfully installed fastapi-0.94.1

[+] xformers version 0.0.17 installed.
[+] torch version 2.0.0+cu118 installed.
[+] torchvision version 0.15.1+cu118 installed.
[+] accelerate version 0.21.0 installed.
[+] diffusers version 0.19.3 installed.
[+] transformers version 4.30.2 installed.
[+] bitsandbytes version 0.35.4 installed.
Launching Web UI with arguments: --xformers --theme dark --disable-safe-unpickle --no-half-vae --disable-nan-check
D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\pkg_resources\__init__.py:123: PkgResourcesDeprecationWarning: llow is an invalid version and will not be supported in a future release
  warnings.warn(
=================================================================================
You are running xformers 0.0.17.
The program is tested to work with xformers 0.0.20.
To reinstall the desired version, run with commandline flag --reinstall-xformers.

Use --skip-version-check commandline argument to disable this check.
=================================================================================
[-] ADetailer initialized. version: 23.7.7, num models: 9
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 18371.79it/s]
[AddNet] Updating model hashes...
100%|███████████████████████████████████████████████████████████████████████████████| 73/73 [00:00<00:00, 18371.79it/s]
dirname:  D:\Ai_program\stable-diffusion-webui\localizations
localizations:  {'zh_CN': 'D:\\Ai_program\\stable-diffusion-webui\\extensions\\stable-diffusion-webui-localization-zh_CN\\localizations\\zh_CN.json'}
2023-09-04 13:53:29,608 - ControlNet - INFO - ControlNet v1.1.313
ControlNet preprocessor location: D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-04 13:53:29,680 - ControlNet - INFO - ControlNet v1.1.313
Loading FABRIC v0.4.0
Loading weights [8035b51710] from D:\Ai_program\stable-diffusion-webui\models\Stable-diffusion\0.7(3Dcartoon_RANSnigi2) + 0.3(ReV_Animated_revAnimated_v122).safetensors
Creating model from config: D:\Ai_program\stable-diffusion-webui\configs\v1-inference.yaml
Couldn't find VAE named kl-f8-anime2.ckpt; using None instead
Model loaded in 3.5s (create model: 0.2s, apply weights to model: 1.8s, apply half(): 0.7s, load VAE: 0.1s, calculate empty prompt: 0.6s).
Applying attention optimization: Doggettx... done.
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py:99: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.selected_img_display = gr.Image(value=None, type="pil", label="Selected image").style(height=256)
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py:106: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  upload_img_input = gr.Image(type="pil", label="Upload image").style(height=256)
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py:118: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  like_gallery = gr.Gallery(label="Liked images", elem_id="fabric_like_gallery").style(columns=4, height=128)
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-fabric\scripts\fabric.py:123: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  dislike_gallery = gr.Gallery(label="Disliked images", elem_id="fabric_dislike_gallery").style(columns=4, height=128)
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:399: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-additional-networks\scripts\metadata_editor.py:521: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  cover_image = gr.Image(
D:\Ai_program\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:257: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
CUDA SETUP: Loading binary D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\bitsandbytes\libbitsandbytes_cudaall.dll...
D:\Ai_program\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:1047: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  db_gallery = gr.Gallery(
D:\Ai_program\stable-diffusion-webui\extensions\sd_dreambooth_extension\scripts\main.py:1047: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  db_gallery = gr.Gallery(
D:\Ai_program\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\main.py:218: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  with gr.Row().style(equal_height=False):
D:\Ai_program\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\block_dataset_gallery.py:25: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.gl_dataset_images = gr.Gallery(label='Dataset Images', elem_id="dataset_tag_editor_dataset_gallery").style(grid=image_columns)
D:\Ai_program\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\block_dataset_gallery.py:25: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  self.gl_dataset_images = gr.Gallery(label='Dataset Images', elem_id="dataset_tag_editor_dataset_gallery").style(grid=image_columns)
D:\Ai_program\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\tab_filter_by_selection.py:35: GradioDeprecationWarning: The `style` method is deprecated. Please set these arguments in the constructor instead.
  self.gl_filter_images = gr.Gallery(label='Filter Images', elem_id="dataset_tag_editor_filter_gallery").style(grid=image_columns)
D:\Ai_program\stable-diffusion-webui\extensions\stable-diffusion-webui-dataset-tag-editor\scripts\tag_editor_ui\tab_filter_by_selection.py:35: GradioDeprecationWarning: The 'grid' parameter will be deprecated. Please use 'columns' in the constructor instead.
  self.gl_filter_images = gr.Gallery(label='Filter Images', elem_id="dataset_tag_editor_filter_gallery").style(grid=image_columns)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 35.1s (prepare environment: 20.8s, import torch: 3.9s, import gradio: 0.5s, setup paths: 0.3s, initialize shared: 0.3s, other imports: 0.4s, load scripts: 7.8s, create ui: 0.7s, gradio launch: 0.3s).
Loading D:\Ai_program\stable-diffusion-webui\models\Stable-diffusion\TJgricon01\TJgricon01_11520.safetensors...
Traceback (most recent call last):
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Ai_program\stable-diffusion-webui\venv\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "D:\Ai_program\stable-diffusion-webui\extensions\sd-webui-model-converter\scripts\convert.py", line 190, in do_convert
    conv_func = _g_precision_func[precision]
TypeError: unhashable type: 'list'

error occured while converting a version1.5 model
![error_snapeshot](https://github.com/Akegarasu/sd-webui-model-converter/assets/127438360/e0ac4c9f-1388-40a7-a25d-a78103c45617)

**Comment by Akegarasu** [comment]
disable translation extension.
