### ISSUE TITLE
Checkpoint Format Checkbox Group Error

### ISSUE THREAD

**Issue by Glen-O** [Akegarasu/sd-webui-model-converter#3]
I tried to use the Model Converter extension, and found that it was misbehaving - in particular, it ignored the Checkpoint Format choice, and created the ckpt file four times. I looked into it, and found the error - on line 71 of the convert.py script, it says

value="ckpt"

It should say

value=["ckpt"]

As it currently stands, it stores the value as "ckpt" and ignores the options, and then when you run the converter, it reads "ckpt" as a list of four characters, and because none of those characters is "safetensors", it saves as ckpt each time through the loop over the list.

Unfortunately, I'm not experienced with Github, so I don't know how to offer an update properly, so posting it as an issue will have to do.

**Comment by Akegarasu** [comment]
I can't reproduce this bug. which commit you're using?

**Comment by Glen-O** [comment]
The current one - be2cd03f3aeda25e1ebd10a2b5202f385427d0f6

I'm using Firefox, maybe that's it? I'm also on a Linux distro, just in case that's where the difference is. I'm loading up Chromium now to see if it does the same thing there.

**Comment by Glen-O** [comment]
Update - yep, works as expected in Chromium, but glitches in Firefox.

**Comment by Glen-O** [comment]
OK, cancel that - Chromium doesn't work correctly, either. It was also just remembering the altered version I had loaded to test.

Maybe it's an OS thing?

**Comment by Akegarasu** [comment]
I've tested in debian 11, it works properly.

**Comment by Glen-O** [comment]
I'm thinking it might be the gradio version. I'm going to try upgrading to the newest version, and see what happens.

**Comment by Glen-O** [comment]
OK, I am fighting with it to try to get it to actually upgrade it and keep it upgraded - it keeps reverting when I load webui... but I had a look at the gradio changelog, and it looks like it was "fixed" in 3.15 (https://www.gradio.app/changelog/ - look for CheckboxGroup). So it seems the code, as it stands, requires 3.15 (although the change I proposed will make it work with earlier versions).

**Comment by Akegarasu** [comment]
confirmed. [Wrap value in list for CheckBoxGroup](https://github.com/gradio-app/gradio/pull/2866)

**Comment by Glen-O** [comment]
Incidentally, I figured out what kept forcing my gradio to downgrade back to 3.9... it was the dreambooth extension.
