### ISSUE TITLE
What is in the "Others" part of the model

### ISSUE THREAD

**Issue by realstevewarner** [Akegarasu/sd-webui-model-converter#6]
Hello!  Thank you for this extremely helpful extension!  I am not a technical person, so I apologize for what may be a stupid question.  I have a model that I've converted, but in order to get it to work outside Automatic1111, I had to delete the "Others" option in the Extras section of your conversion tool.  That worked great, but I wanted to know what the "Others" section contains.  Can you tell me what the "Others" part of the model is?  Also, it is this part of the model that is breaking some ckpt files for use outside of Automatic1111.  Stripping the Others out makes these models work elsewhere.  My next question is how can I convert the "Others" data into a format that can be used outside of A1111.  I've tried using the convert method to no avail.  Also, I am able to create a model with only the "Others" data in it.  It works in A1111, but not in anything else.  In short, I want to convert this "Others" data, it is causing many models to fail to work outside A1111.  Thank you for your help!

**Comment by Akegarasu** [comment]
Any other weights that is not one of these will be included into "others"：
- model.diffusion_model (unet)
- first_stage_model (vae)
- cond_stage_model (clip)

You can find this part of code [here](https://github.com/Akegarasu/sd-webui-model-converter/blob/main/scripts/convert.py#L38)

Usually, it's some weight for plms and ddpm sampler. But sometimes some wrong weights may also be added to the mode, these will be included into "Others". Like NovelAI's model, there's a "state_dict" key in it.

**Comment by realstevewarner** [comment]
Thank you very much for the detailed reply!  Is it safe to say that the
"Others" part of a model isn't contributing much to the image generation?
I had to leave out the "Others" part of a model to get it to work in
InvokeAI.  It's running great.  Just trying to figure out if I'm
missing something critical.

Thank you again!
